# Generated by Django 4.1.2 on 2023-04-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на русском')),
                ('name_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на английском')),
                ('name_kk', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на казахском')),
                ('name_kk_lat', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на казахском (латиница)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Когда удалена запись')),
                ('message', models.TextField(verbose_name='Текст заявки')),
                ('sender_id', models.IntegerField(blank=True, null=True, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка на добавление мема',
                'verbose_name_plural': 'Заявки на добавление мемов',
            },
        ),
    ]
