# Generated by Django 4.1.2 on 2023-04-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memes', verbose_name='Картинка с мемом'),
        ),
        migrations.AlterField(
            model_name='memesrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст заявки'),
        ),
    ]
