# Generated by Django 4.1.2 on 2023-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_memesrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memes', verbose_name='Картинка с мемом'),
        ),
    ]
